### ISSUE TITLE
Broken Context Menu Actions?

### ISSUE THREAD

**Issue by matthew-t-johnson** [loiane/angular-extension-pack-vsce#3]
I'm wondering if the right-click/context menu actions *(i.e. "ng g component", "ng g directive", etc.)* are broken, possibly with a recent VS Code update?

I was originally working on a Windows desktop and these options were listed, but on my Windows laptop these context menu actions don't display, despite also having this extension pack installed here. 

Just confused because the various "Barrel" commands remain visible, but these are now gone. 

*The [YouTube video that suggested this extension](https://www.youtube.com/watch?v=3dcpbMkRlAk) implied this feature was included in the pack, so I'm sorry if I'm mistaken*

**Comment by loiane** [comment]
Hi, 
The extension responsible for this functionality is this one: https://marketplace.visualstudio.com/items?itemName=AngularDoc.angulardoc-vscode

As since angular v6+, the structure of the CLI project has been updated, so the context menu is no longer working. Instead, a new context menu option has been added: Schematics. You can click on it, select the angular schematics and then you have all the options that were previously available.
